- name: Secondary MX OpenSMTPD Configuration
  hosts:
    - mx2
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: Configure OpenSMTPD smtpd.conf
      template:
        src: "templates/secondary-smtpd.conf"
        dest: /etc/mail/smtpd.conf
      notify:
        - reload smtpd

    - name: Enable and start OpenSMTPD service
      service:
        name: smtpd
        enabled: yes
        state: started

  handlers:
    - name: reload smtpd
      service:
        name: smtpd
        state: restarted
