- name: VPN Setup
  hosts:
    - mx1
    - mx2
  remote_user: root
  vars_files:
    - vars.yml
  tasks:
    - name: Install node-exporter
      community.general.openbsd_pkg:
        name:
          - node_exporter
        state: present

    - name: Enable and start node_exporter
      service:
        name: node_exporter
        enabled: yes
        state: started
